<?php $LinkedinProfile = $block->getLayout()->createBlock('RedboxDigital\Customer\Block\Widget\LinkedinProfile') ?>
<?php if ($LinkedinProfile->isEnabled()): ?>
<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */  echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */   echo __('Additional Information') ?></span></legend>
	<?php echo $LinkedinProfile->toHtml() ?>
</fieldset>
<?php endif ?>